language: java
before_install:
   - mvn install:install-file -Dfile=pojo-modelutil-2.2.0.jar -DgroupId=es.udc.pojo -DartifactId=pojo-modelutil -Dversion=1 -Dpackaging=jar
services:
   mysql
jdk:
   oraclejdk8
install: mvn -e test
notifications:
   email: false
